In [1]:
import numpy as np
import pandas as pd
df = pd.read_csv('Mental_Health_and_Social_Media_Balance_Dataset.csv')
df

,User_ID,Age,Gender,Daily_Screen_Time(hrs),Sleep_Quality(1-10),Stress_Level(1-10),Days_Without_Social_Media,Exercise_Frequency(week),Social_Media_Platform,Happiness_Index(1-10)
0,U001,44,Male,3.1,7.0,6.0,2.0,5.0,Facebook,10.0
1,U002,30,Other,5.1,7.0,8.0,5.0,3.0,LinkedIn,10.0
2,U003,23,Other,7.4,6.0,7.0,1.0,3.0,YouTube,6.0
3,U004,36,Female,5.7,7.0,8.0,1.0,1.0,TikTok,8.0
4,U005,34,Female,7.0,4.0,7.0,5.0,1.0,X (Twitter),8.0
...,...,...,...,...,...,...,...,...,...,...
495,U496,23,Male,6.9,5.0,7.0,4.0,2.0,X (Twitter),10.0
496,U497,43,Female,5.6,7.0,6.0,5.0,2.0,Facebook,9.0
497,U498,41,Male,7.7,5.0,7.0,2.0,2.0,LinkedIn,8.0
498,U499,23,Male,4.2,9.0,7.0,0.0,2.0,Facebook,9.0
499,U500,43,Female,5.9,5.0,8.0,3.0,3.0,X (Twitter),7.0

In [2]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
df = df.replace(0, pd.NA).dropna()
df = df.select_dtypes(include="number")
df.head()

,age,daily_screen_time(hrs),sleep_quality(1-10),stress_level(1-10),happiness_index(1-10)
0,44,3.1,7.0,6.0,10.0
1,30,5.1,7.0,8.0,10.0
2,23,7.4,6.0,7.0,6.0
3,36,5.7,7.0,8.0,8.0
4,34,7.0,4.0,7.0,8.0

In [3]:
from sklearn.model_selection import train_test_split

X = df.drop(columns=["stress_level(1-10)"])
y = df["stress_level(1-10)"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [4]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [5]:
from sklearn.metrics import mean_absolute_percentage_error, mean_absolute_error, r2_score

y_pred = model.predict(X_test)

mape = mean_absolute_percentage_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"MAPE: {mape*100:.2f}%")
print(f"MAE: {mae:.3f}")
print(f"R²: {r2:.3f}")

MAPE: 13.68%
MAE: 0.839
R²: 0.567

In [6]:
sample = pd.DataFrame([{
    "age": 44,
    "daily_screen_time(hrs)": 3.1,
    "sleep_quality(1-10)": 7,
    "happiness_index(1-10)": 10
}])
pred = model.predict(sample)[0]
print(f"Predicted Stress Level: {pred:.2f}")

Predicted Stress Level: 4.95